### ISSUE TITLE
小米WIFI二维码分享密码页面强制亮度

### ISSUE THREAD

**Issue by Kukuair** [Xposed-Modules-Repo/com.fankes.refusebrightness#1]
请问可以添加  拒绝小米WIFI二维码分享密码页面强制亮度  的功能吗？我尝试勾选 com.android.settings  但是WIFI二维码分享密码页面仍然强制亮度显示

![IMG_20220423_193519](https://user-images.githubusercontent.com/57177286/164892996-71729727-175c-4278-82a8-6070c52c8f96.jpg)

**Comment by ghost** [comment]
我这没问题 V13.0.1

**Comment by Kukuair** [comment]
强制停止设置(com.android.settings) 后可行
